@startuml
Vehicle : String paintColors
Vehicle : int vehicle
Vehicle : String vehicleType
Vehicle : int motif
Vehicle : int speed
Vehicle : int suspension
Vehicle : setOrder()
Vehicle : getOrder()
Passenger : int passenger
Passenger : int riseTime
Passenger : int downTime
Passenger : String vehicleType
Passenger : setPassenger()
Passenger : setCivilians()
Passenger : setPublicFacilities()
MotorVehicle : String engineType
MotorVehicle : int weight
MotorVehicle : int maxWeight
MotorVehicle : String nos
MotorVehicle : setVehicleType()
MotorVehicle : setSpeed()
NonMotorVehicle : int NonMotorVehicleType
NonMotorVehicle : int wheelSize
NonMotorVehicle : int weight
NonMotorVehicle : int maxWeight
NonMotorVehicle : String vehicleType
NonMotorVehicle : String nos
NonMotorVehicle : setVehicleType()
NonMotorVehicle : getSpeed()
Point : int point
Point : getOrder()
Point : getPoint()
Point : getCrashInfo()
Point : getWinner()
Money : int transaction
Money : getBonus()
Money : getOrder()
Money : getVehicleType()
Bonus : int bonus
Bonus : int getNumberOfPassenger
Bonus : riseTime
Bonus : downTime
Bonus : setBonus()
Order : int order
Order : setOrder()
Player : String player
Player : int totalSpeed
Player : String vehicleType
Player : getMoney()
Player : getBonus()
Player : getOrder()
Player : getBreakTime()
Player : getPassenger()
MotorVehicle --|> Vehicle
NonMotorVehicle --|> Vehicle
Vehicle --> Point
Bonus --> Money
Passenger --> Bonus
Vehicle --> Passenger
Order --> Money
Order --> Point
Vehicle <--> Player
Point --> Player
Passenger --> Player
@enduml