@startuml
Vehicle : String colour
Vehicle : int speed
Vehicle : int weight
Vehicle : int passenger
Vehicle : int maxWeight
Vehicle : turnLeft()
Vehicle : turnRight()
Passenger : int weight
Bicycle : int wheelSize
MotorVehicle : String engineType
FourWheel --|> MotorVehicle
Truck --|> FourWheel
Car --|> FourWheel
TwoWheel --|> MotorVehicle
Bicycle --|> Vehicle
Vehicle -- Passenger
MotorVehicle --|> Vehicle
@enduml