@startuml
Camera : String ip
Camera : getPicture()
Camera : getLicenseNumber()

ControlSystem : printInvoice()
ControlSystem : getPaid()
ControlSystem : setPaid()
ControlSystem : getPrice()
ControlSystem : save()

Ticket : String no
Ticket : startTime
Ticket : endTime
Ticket : print()
Ticket : getBarcode()

Gate : int status
Gate : openGate()
Gate : closeGate()
Gate : getStatus()

Camera -- ControlSystem
Gate -- ControlSystem
Ticket -- ControlSystem
@enduml