@startuml
Vehicle : int number
Vehicle : DateTime timeIn
Vehicle : DateTime timeOut

Camera : String ip
Camera : getPicture()
Camera : getLicenseNumber()

ControlSystem : printInvoice()
ControlSystem : getPaid()
ControlSystem : setPaid()
ControlSystem : getPrice()

Ticket : String no
Ticket : print()
Ticket : getBarcode()

Gate : int status
Gate : openGate()
Gate : closeGate()
Gate : getStatus()

Operator : name
Operator : sex
Operator : email
Operator : name

Camera -- ControlSystem
Gate -- ControlSystem
Ticket -- ControlSystem
Vehicle -- ControlSystem
Operator -- ControlSystem
@enduml