@startuml
Vehicle : int number

Camera : String ip
Camera : getPicture()
Camera : getLicenseNumber()

CheckIn : DateTime timeIn
CheckIn : Vehicle vehicle

CheckOut : DateTime timeOut
CheckOut : Vehicle vehicle
CheckOut : getCost()
CheckOut : setPaid()

Ticket : String no
Ticket : print()
Ticket : getBarcode()

Gate : int status
Gate : openGate()
Gate : closeGate()
Gate : getStatus()

Vehicle -- CheckIn
Vehicle -- CheckOut
Vehicle -- Camera
Ticket -- CheckIn
@enduml