@startuml
ParkedMachine : openGate()
ParkedMachine : closeGate()
ParkedMachine : printReceipt()

Vehicle : int number
Vehicle : DateTime timeIn
Vehicle : DateTime timeOut

Camera : String ip
Camera : getPicture()
Camera : getLicenseNumber()

ControlSystem : printInvoice()
ControlSystem : getPaid()
ControlSystem : setPaid()
ControlSystem : getPrice()

Ticket : String no
Ticket : print()
Ticket : getBarcode()

Camera -- ControlSystem
Ticket -- ControlSystem
Vehicle -- ControlSystem
ParkedMachine -- ControlSystem
@enduml