@startuml
ParkedCar : int licenseNum
ParkedCar : int numOfMinutesParked
ParkedCar : DateTime timeIn
ParkedCar : DateTime timeOut
ParkedCar : getLicenseNum()
ParkedCar : getNumOfMinutesParked()

Camera : String ip
Camera : getPicture()
Camera : getLicenseNumber()

ControlSystem : printInvoice()
ControlSystem : getPaid()
ControlSystem : setPaid()
ControlSystem : getPrice()

Ticket : String no
Ticket : print()
Ticket : getBarcode()

Gate : int status
Gate : openGate()
Gate : closeGate()
Gate : getStatus()

Camera -- ControlSystem
Gate -- ControlSystem
Ticket -- ControlSystem
ParkedCar -- ControlSystem
@enduml