@startuml
ControlSystem : calculatePayment()
ControlSystem : calculateTime()
Driver : getTicket()
Driver : payTicket()
GateOperator : checkTicket()
ParkingArea : getAreaNumber()
Machine : giveTicket()
Driver -- ControlSystem
GateOperator -- ControlSystem
ParkingArea -- ControlSystem
Machine -- ControlSystem
Camera : ip
Camera : getPicture()
Camera : getLicenseNumber()
ControlSystem : printInvoice()
ControlSystem : getPaid()
ControlSystem : setPaid()
ControlSystem : getPrice()
Ticket : no
Ticket : print()
Ticket : getBarcode()
Gate : status
Gate : openGate()
Gate : closeGate()
Gate : getStatus()
Camera -- ControlSystem
Gate -- ControlSystem
Ticket -- ControlSystem
@enduml