@startuml
Camera : ip
Gate : openGate()
Gate : closeGate()
Ticket
Car
numberLicense
Date dateIn
Date dateOut
id
getCapture
setCapture
id
Date dateIn
statusGate
Employee
id
name
checkValidateTicket
Server
getCaptureCamera
calculatePrice
TicketMachine
printTicket
Car|*..>|numberLicense
Car|*..>|Date dateIn
Car|*..>|Date dateOut
Camera|*..>|id
Camera|:|getCapture
Camera|:|setCapture
Ticket|*..>|id
Ticket|*..>|Date dateIn
Gate|*..>|statusGate
Employee|*..>|id
Employee|*..>|name
Employee|:|checkValidateTicket
Server|:|getCaptureCamera
Server|:|calculatePrice
TicketMachine|:|printTicket
Car|-->|Ticket
Car|-->|TicketMachine
Car|-->|Employee
Car|-->|Gate
Employee|-->|Ticket
Employee|-->|Server
Employee|-->|Gate
Camera|-->|Car
Camera|-->|Server
TicketMachine|--|>|Ticket
TicketMachine|-->|Gate
@enduml