@startuml
Patient : name
Employee : name
Doctor --|> Employee
Nurse --|> Employee
Staff --|> Employee
Pharmacist --|> Employee
Medicine : name
MedicalTreatment : name
Blling -- Patient
Blling -- MedicalThreatment
MedicalRecord -- Patient 
Stock : date
Stock -- Medicine
@enduml