/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisapp;

import com.jgraph.layout.JGraphFacade;
import com.jgraph.layout.JGraphLayout;
import com.jgraph.layout.hierarchical.JGraphHierarchicalLayout;
import graphmodel.RelationshipEdge;
import java.awt.Dimension;
import java.util.Map;
import javax.swing.JApplet;
import model.Dataset;
import org.jgraph.JGraph;
import org.jgrapht.DirectedGraph;
import org.jgrapht.ext.JGraphModelAdapter;

/**
 *
 * @author Momo
 */
public class JInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame
     */
    public JInternalFrame() {
        initComponents();
        Dataset app0 = new Dataset();
        app0.readFile("parkiran", "case10.puml");
        DirectedGraph dg = app0.getGraph();
        
        JGraphModelAdapter<Object, RelationshipEdge> jgAdapter = new JGraphModelAdapter<Object, RelationshipEdge>(dg);

        JGraph jgraph = new JGraph(jgAdapter);
        JApplet applet = new JApplet();
        getContentPane().add(applet);
        applet.getContentPane().add(jgraph);
        applet.resize(new Dimension(530, 320));
        JGraphLayout layout = new JGraphHierarchicalLayout();
        
        JGraphFacade facade = new JGraphFacade(jgraph);
        layout.run(facade);
        Map nested = facade.createNestedMap(false, false);
        jgraph.getGraphLayoutCache().edit(nested);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
